name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -f Dockerfile_dev -t evan-app .   #123

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519.pem
        chmod 600 ~/.ssh/id_ed25519.pem

    - name: Debug SSH key
      run: |
        ls -l ~/.ssh  # 列出 .ssh 目录
        cat ~/.ssh/id_ed25519.pem  # 检查私钥内容（可选，仅用于调试）
        ssh-keygen -y -f ~/.ssh/id_ed25519.pem  # 提取公钥，检查是否匹配 123

    - name: Add Host Key
      run: |
        ssh-keyscan -H 20.55.25.167 >> ~/.ssh/known_hosts

    - name: Deploy to Azure VM
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519.pem ./Dockerfile_dev Evan1923@20.55.25.167:/home/Evan1923/say66_dev/
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519.pem Evan1923@20.55.25.167 "
          cd /home/Evan1923/say66_dev &&
          mv Dockerfile_dev Dockerfile &&
          docker stop evan || true &&
          docker rm evan || true &&
          docker build -t evan-app . &&
          docker run -d -p 5000:5000 --name evan evan-app
        "
