name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519.pem
        chmod 600 ~/.ssh/id_ed25519.pem

        # 验证私钥是否正确生成
        ls -l ~/.ssh
        ssh-keygen -y -f ~/.ssh/id_ed25519.pem || echo "Failed to load private key"

    - name: Add Host Key
      run: |
        ssh-keyscan -H 20.248.241.202 >> ~/.ssh/known_hosts

    - name: Deploy to Azure VM
      run: |
          # Ensure the remote directory exists before copying
          ssh -i ~/.ssh/id_ed25519.pem evan1923@20.248.241.202 "mkdir -p /home/evan1923/say66_dev/"
      
          # Copy the Dockerfile_dev to the remote server
          scp -i ~/.ssh/id_ed25519.pem -r ./Dockerfile_dev evan1923@20.248.241.202:/home/evan1923/say66_dev/
      
          # SSH into the server and deploy the Docker container
          ssh -i ~/.ssh/id_ed25519.pem evan1923@20.248.241.202 "
            cd /home/evan1923/say66_dev &&
            mv Dockerfile_dev Dockerfile &&
            docker stop evan || true &&
            docker rm evan || true &&
            docker build --no-cache -t evan-app . &&
            docker run -d -p 5000:5000 --name evan evan-app
          "
      
